stages:
  - build
  - test
  - image
  - deploy

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - vendor/
    - tmp/

build_code:
  stage: build
  image: hub.ahss.io/ahss/ant:5.6.23
  script:
    - bash bin/composer.sh

quick_test:
  stage: test
  image: hub.ahss.io/ahss/ant:5.6.23
  script:
    - bash bin/composer.sh
    - ant phpunit

# full_test:
#   stage: test
#   image: hub.ahss.io/ahss/ant:5.6.23
#   script:
#     - bash bin/composer.sh
#     - bash bin/gitlab-full-test.sh
#   only:
#     - master
#
# build_image:
#   stage: image
#   script:
#     - docker build --rm -t hub.ahss.io/ahss/fh-neuroscience:develop .
#     - docker login --username="tsms01" --password="$HUB_PASSWORD" hub.ahss.io
#     - docker push hub.ahss.io/ahss/fh-neuroscience:develop
#   only:
#     - develop
#     - master
#
# deploy_image:
#   stage: deploy
#   script:
#     - docker rm -f $CI_PROJECT_ID || echo 'No container to remove'
#     - docker pull hub.ahss.io/ahss/fh-neuroscience:develop
#     - docker run -it -d -p 80 --label interlock.hostname="fh-neuroscience" --label interlock.domain="dev.ahss.io" --restart="always" --name="$CI_PROJECT_ID" hub.ahss.io/ahss/fh-neuroscience:develop
#   only:
#     - develop
#     - master

variables:
    SIMPLETEST_DB: sqlite://tmp/site.sqlite
    SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
    COMPOSER_CACHE_DIR : "./tmp"
    COMPOSER_ALLOW_SUPERUSER: "1"
